name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Start SUT
        # Запускаем System Under Test (SUT) в фоновом режиме
        run: java -jar ./artifacts/app-replan-delivery.jar &

      - name: Build and run tests with Gradle
        # Запускаем автотесты с параметром для headless-режима
        run: ./gradlew test --info -Dselenide.headless=true
